const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const request = require("supertest");

const app = require("../index");
const { inspectImage, addressKey, AVATAR_DIR } = require("../routes/avatar");
const {
  AUTHORIZATION_DOMAIN,
  addressFromPublicKey,
  authorizationMessage,
  bodyHash,
  resetUsedNoncesForTests,
} = require("../middleware/signedAuthorization");

// A real 8x8 RGB PNG (72 bytes), generated by zlib — small but structurally valid.
const PNG_B64 = "iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAIAAABLbSncAAAAD0lEQVR4nGM4gQMwDC0JAJwulgGh6TLjAAAAAElFTkSuQmCC";
const PNG_BUFFER = Buffer.from(PNG_B64, "base64");

function makeWallet() {
  const { privateKey, publicKey } = crypto.generateKeyPairSync("ec", { namedCurve: "secp256k1" });
  const public_key = publicKey.export({ format: "pem", type: "spki" });
  return { privateKey, public_key, wallet: addressFromPublicKey(public_key) };
}

function signAvatar(signer, body) {
  const timestamp = Math.floor(Date.now() / 1000);
  const nonce = `nonce-${crypto.randomUUID()}`;
  const hash = bodyHash(body);
  const message = authorizationMessage({ action: "profile.avatar", body_hash: hash, nonce, timestamp, wallet: signer.wallet });
  const signature = crypto.sign("sha256", Buffer.from(message, "utf8"), signer.privateKey).toString("hex");
  return {
    ...body,
    authorization: {
      wallet: signer.wallet,
      public_key: signer.public_key,
      signature,
      message,
      timestamp,
      nonce,
      action: "profile.avatar",
      body_hash: hash,
      domain: AUTHORIZATION_DOMAIN,
    },
  };
}

function cleanupAvatar(address) {
  for (const ext of ["png", "jpg", "jpeg", "webp", "gif"]) {
    const file = path.join(AVATAR_DIR, `${addressKey(address)}.${ext}`);
    try {
      if (fs.existsSync(file)) fs.unlinkSync(file);
    } catch (error) {
      /* ignore */
    }
  }
}

beforeEach(() => resetUsedNoncesForTests());

describe("inspectImage", () => {
  test("accepts a real PNG and reads its dimensions", () => {
    const info = inspectImage(PNG_BUFFER);
    expect(info).toMatchObject({ ext: "png", mime: "image/png", width: 8, height: 8 });
  });

  test("rejects a non-image buffer (disguised script)", () => {
    expect(inspectImage(Buffer.from("<script>alert(1)</script> not an image at all"))).toBeNull();
  });

  test("rejects an SVG (script vector)", () => {
    expect(inspectImage(Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"></svg>'))).toBeNull();
  });
});

describe("POST /api/profiles/avatar", () => {
  test("stores a signed PNG upload and serves it back", async () => {
    const signer = makeWallet();
    cleanupAvatar(signer.wallet);
    const body = signAvatar(signer, { wallet_address: signer.wallet, image: `data:image/png;base64,${PNG_B64}` });

    const response = await request(app).post("/api/profiles/avatar").send(body);
    expect(response.status).toBe(200);
    expect(response.body.success).toBe(true);
    expect(response.body.url).toContain(encodeURIComponent(signer.wallet));

    const fetched = await request(app).get("/api/profiles/avatar").query({ address: signer.wallet });
    expect(fetched.status).toBe(200);
    expect(fetched.headers["content-type"]).toContain("image/png");

    cleanupAvatar(signer.wallet);
  });

  test("rejects an unsigned upload (signed authorization required)", async () => {
    const signer = makeWallet();
    const response = await request(app)
      .post("/api/profiles/avatar")
      .send({ wallet_address: signer.wallet, image: PNG_B64 });
    expect(response.status).toBe(503);
    expect(response.body.error.code).toBe("SIGNED_AUTHORIZATION_REQUIRED");
  });

  test("rejects a non-image payload even when properly signed", async () => {
    const signer = makeWallet();
    const fakeImage = Buffer.from(`#!/bin/sh\n${"echo definitely not an image payload ".repeat(8)}`).toString("base64");
    const body = signAvatar(signer, { wallet_address: signer.wallet, image: fakeImage });

    const response = await request(app).post("/api/profiles/avatar").send(body);
    expect(response.status).toBe(415);
    expect(response.body.error.code).toBe("UNSUPPORTED_IMAGE");
  });

  test("rejects an image whose declared dimensions exceed the cap", async () => {
    const signer = makeWallet();
    const oversized = Buffer.from(PNG_BUFFER);
    oversized.writeUInt32BE(4000, 16); // overwrite IHDR width
    oversized.writeUInt32BE(4000, 20); // overwrite IHDR height
    const body = signAvatar(signer, { wallet_address: signer.wallet, image: oversized.toString("base64") });

    const response = await request(app).post("/api/profiles/avatar").send(body);
    expect(response.status).toBe(422);
    expect(response.body.error.code).toBe("IMAGE_DIMENSIONS");
  });

  test("a wallet cannot overwrite another wallet's avatar", async () => {
    const owner = makeWallet();
    const attacker = makeWallet();
    // Attacker signs with their own key but claims the owner's address.
    const body = signAvatar(attacker, { wallet_address: owner.wallet, image: PNG_B64 });

    const response = await request(app).post("/api/profiles/avatar").send(body);
    expect(response.status).toBe(401);
    expect(response.body.error.code).toBe("AUTHORIZATION_ACTOR_MISMATCH");
  });
});
