server {
    listen 80;
    server_name status.vorliq.org;

    root /home/vorliq/app/docs;
    index status.html;

    location / {
        try_files /status.html =404;
    }

    location = /logo.png {
        try_files /logo.png =404;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json;
}
