import { createPythonSigningPayload, extractSecp256k1PrivateScalar, signMessage, signTransaction } from "./signer";

// A real SECP256K1 key generated by the chain (see walletFromPrivateKey.test.js),
// so the browser signer is exercised end to end, not just its guard clauses.
const PRIVATE_KEY_PEM = `-----BEGIN PRIVATE KEY-----
MIGEAgEAMBAGByqGSM49AgEGBSuBBAAKBG0wawIBAQQgd5YYdfUJahkiKysEUVSb
w8AEwDT8/8uMK97e0mF0QPChRANCAATPKGhjZjOg966bfk/CKy6wrWM1IHhbul09
Ck3lLjvgPQuq89ihk7ibS7AXaLOHmteM47L2BSMrRyuNuCRsDUFy
-----END PRIVATE KEY-----`;

describe("createPythonSigningPayload", () => {
  test("renders integer amounts with a trailing .0 to match the Python serializer", () => {
    const payload = createPythonSigningPayload({
      senderAddress: "VLQ_A",
      receiverAddress: "VLQ_B",
      amount: 5,
      timestamp: 1700000000,
    });
    expect(payload).toBe(
      '{"amount":5.0,"receiver_address":"VLQ_B","sender_address":"VLQ_A","timestamp":1700000000}'
    );
  });

  test("renders fractional amounts as-is and orders keys canonically", () => {
    const payload = createPythonSigningPayload({
      senderAddress: "VLQ_A",
      receiverAddress: "VLQ_B",
      amount: 5.5,
      timestamp: 1700000000,
    });
    expect(payload).toContain('"amount":5.5');
    // Key order must be amount, receiver, sender, timestamp (matches the node).
    expect(payload.indexOf('"amount"')).toBeLessThan(payload.indexOf('"receiver_address"'));
    expect(payload.indexOf('"receiver_address"')).toBeLessThan(payload.indexOf('"sender_address"'));
    expect(payload.indexOf('"sender_address"')).toBeLessThan(payload.indexOf('"timestamp"'));
  });

  test("rejects a non-numeric amount", () => {
    expect(() =>
      createPythonSigningPayload({ senderAddress: "a", receiverAddress: "b", amount: "abc", timestamp: 1 })
    ).toThrow(/valid number/i);
  });
});

describe("extractSecp256k1PrivateScalar", () => {
  test("throws on an empty PEM body", () => {
    expect(() => extractSecp256k1PrivateScalar("-----BEGIN PRIVATE KEY-----\n-----END PRIVATE KEY-----"))
      .toThrow(/empty or invalid/i);
  });

  test("throws when no SECP256K1 scalar marker is present", () => {
    // Valid base64 that decodes to bytes without the 0x04 0x20 scalar prefix.
    const pem = `-----BEGIN PRIVATE KEY-----\n${window.btoa("hello world not a real key")}\n-----END PRIVATE KEY-----`;
    expect(() => extractSecp256k1PrivateScalar(pem)).toThrow(/could not read a secp256k1/i);
  });

  test("extracts a 32-byte (64-hex) scalar from a real key", () => {
    expect(extractSecp256k1PrivateScalar(PRIVATE_KEY_PEM)).toMatch(/^[0-9a-f]{64}$/);
  });
});

describe("signing", () => {
  test("signMessage returns a DER-encoded hex signature", async () => {
    const signature = await signMessage({ privateKeyPem: PRIVATE_KEY_PEM, message: "hello vorliq" });
    expect(signature).toMatch(/^[0-9a-f]+$/);
    expect(signature.length).toBeGreaterThan(64);
  });

  test("signTransaction returns the full signed transaction envelope", async () => {
    const signed = await signTransaction({
      senderAddress: "VLQ_SENDER",
      senderPrivateKey: PRIVATE_KEY_PEM,
      senderPublicKey: "PUBLIC_KEY_PEM",
      receiverAddress: "VLQ_RECEIVER",
      amount: 5,
    });
    expect(signed.sender_address).toBe("VLQ_SENDER");
    expect(signed.receiver_address).toBe("VLQ_RECEIVER");
    expect(signed.amount).toBe(5);
    expect(signed.signature).toMatch(/^[0-9a-f]+$/);
    expect(typeof signed.timestamp).toBe("number");
  });
});
