import { deriveWalletFromPrivateKey } from "./walletFromPrivateKey";

// Vector generated by the chain itself (blockchain/wallet.py Wallet()), so this
// test fails loudly if the browser derivation ever drifts from the chain's
// address/public-key algorithm.
const CHAIN_PRIVATE_KEY_PEM = `-----BEGIN PRIVATE KEY-----
MIGEAgEAMBAGByqGSM49AgEGBSuBBAAKBG0wawIBAQQgd5YYdfUJahkiKysEUVSb
w8AEwDT8/8uMK97e0mF0QPChRANCAATPKGhjZjOg966bfk/CKy6wrWM1IHhbul09
Ck3lLjvgPQuq89ihk7ibS7AXaLOHmteM47L2BSMrRyuNuCRsDUFy
-----END PRIVATE KEY-----`;
const CHAIN_ADDRESS = "2Vd5aHn7Urus74JoecXxcyxmGtAc";
const CHAIN_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEzyhoY2YzoPeum35PwisusK1jNSB4W7pd
PQpN5S474D0LqvPYoZO4m0uwF2izh5rXjOOy9gUjK0crjbgkbA1Bcg==
-----END PUBLIC KEY-----`;

describe("deriveWalletFromPrivateKey", () => {
  test("derives the chain's exact address and public key from a private key PEM", () => {
    const wallet = deriveWalletFromPrivateKey(CHAIN_PRIVATE_KEY_PEM);
    expect(wallet.address).toBe(CHAIN_ADDRESS);
    expect(wallet.public_key.replace(/\s+/g, "")).toBe(CHAIN_PUBLIC_KEY_PEM.replace(/\s+/g, ""));
    expect(wallet.private_key).toBe(CHAIN_PRIVATE_KEY_PEM);
  });

  test("rejects an empty key with a clear message", () => {
    expect(() => deriveWalletFromPrivateKey("   ")).toThrow(/enter your private key/i);
  });

  test("rejects a malformed PEM with a clear message", () => {
    expect(() => deriveWalletFromPrivateKey("not a pem at all")).toThrow(/valid Vorliq private key|secp256k1/i);
  });

  test("rejects a PEM whose body is not a secp256k1 key", () => {
    const garbage = "-----BEGIN PRIVATE KEY-----\nQUJDREVGR0g=\n-----END PRIVATE KEY-----";
    expect(() => deriveWalletFromPrivateKey(garbage)).toThrow();
  });
});
